# Generated by Django 4.2.16 on 2024-12-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='conversation_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_id',
        ),
    ]
