# Generated by Django 4.2.16 on 2024-12-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_user_password_hash_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
